- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  setPreference: true # Lua
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 9000 #2.5 hrs
  startingGear: ParamedicGear
  alwaysUseSpawner: true
  icon: "JobIconParamedic"
  supervisors: job-supervisors-mmo # Frontier
  access:
  - Medical
  - Maintenance
  - Paramedic
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Nanotrasen

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
