# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

#перенесено в BlueShieldOfficer
# - type: job
#   id: BlueShieldOfficer
#   name: job-name-blue-shield-officer
#   description: job-description-blue-shield-officer
#   playTimeTracker: JobBlueShieldOfficer
#   setPreference: false
#   requirements:
#     - !type:DepartmentTimeRequirement
#       department: Engineering
#       time: 36000 # 10 hours
#     - !type:DepartmentTimeRequirement
#       department: Medical
#       time: 36000 # 10 hours
#     - !type:RoleTimeRequirement
#       role: JobHeadOfSecurity
#       time: 36000 # 10 hours
#     - !type:DepartmentTimeRequirement
#       department: Command
#       time: 36000 # 10 hours
#     - !type:OverallPlaytimeRequirement
#       time: 324000 # 90 hours
#   startingGear: BlueShieldOfficerGear
#   icon: "JobIconBlueShieldOfficer"
#   supervisors: job-supervisors-centcom
#   canBeAntag: false
#   access:
#   - Captain
#   - Command
#   - Brig
#   - Security
#   - Armory
#   - Maintenance
#   - Service
#   - External
#   - Research
#   - Medical
#   - Engineering
#   - Cargo
#   special:
#   - !type:AddImplantSpecial
#     implants: [ MindShieldImplant ]

- type: startingGear
  id: BlueShieldOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBlueShield
    head: ClothingHeadHatBeretBlueShield
    back: ClothingBackpackBlueShield
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCommand
    shoes: ClothingShoesBootsJackFilled
    outerClothing: ClothingOuterArmorBasicBlueShield
    suitstorage: WeaponRifleLecter
    belt: ClothingBeltMilitaryWebbingBlueShieldFilled
    gloves: ClothingHandsGlovesCombat
    id: BlueShieldOfficerPDA
    pocket1: PistolBlueShield

- type: entity
  parent: BasePDA
  id: BlueShieldOfficerPDA
  components:
    - type: Pda
      id: BlueShieldOfficerIDCard
    - type: PdaBorderColor
      borderColor: "#12445b"
      accentHColor: "#772d32"
      accentVColor: "#772d32"
    - type: Icon
      state: pda-ert
    - type: HealthAnalyzer
      scanDelay: 1

- type: entity
  parent: IDCardStandard
  id: BlueShieldOfficerIDCard
  components:
    - type: Sprite
      layers:
        - state: default
        - state: ert_security
    - type: PresetIdCard
      job: BlueShieldOfficer
    - type: Access
      tags:
        - CCSecurity
        - CentralCommand
      groups:
        - AllAccess

- type: entity
  parent: ClothingBackpack
  id: ClothingBackpackBlueShield
  name: модифицированный рюкзак офицера "Синий Щит"
  description: Рюкзак офицера "Синий Щит" с функцией РИГ.
  components:
  - type: Sprite
    sprite: _Lua/Clothing/Back/blueshield.rsi
  - type: Storage
    grid:
    - 0,0,7,5
  - type: ClothingSpeedModifier
    walkModifier: 1
    sprintModifier: 1
  - type: ToggleableClothing
    clothingPrototype: ClothingOuterHardsuitBlueShield
    requiredSlot: BACK
    slot: outerClothing
  - type: ContainerContainer
    containers:
      toggleable-clothing: !type:ContainerSlot {}
      storagebase: !type:Container
        ents: []
  - type: StorageFill
    contents:
      - id: BoxSurvivalSecurity
      - id: Zipties
        amount: 3
      - id: ADTtelescopicBaton # ADT
      - id: NFMagazineSubMachineGun35
        amount: 4
      - id: WeaponSubMachineGunDrozd
      - id: HandheldCrewMonitor
  - type: ExplosionResistance
    damageCoefficient: 0.6
