# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanAtmosTech
  name: job-name-typan-atmos-tech
  playTimeTracker: JobOutpostTypanAtmosTech
  description: Атмосферный инженер из далёкого космоса.
  startingGear: SyndicateAtmos
  icon: "JobIconSyndicateAtmos"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 29000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 24000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10000
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled

- type: startingGear
  id: SyndicateAtmos
  equipment:
    ears: ClothingHeadsetAltOutpostTypan
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    shoes: ClothingShoesBootsOutpostTypan
    back: ClothingBackpackSyndicateFilled
    belt: ClothingBeltAssaultOutpostTypan
    id: SyndiPDAEng
