# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanBotanist
  name: job-name-typan-botanist
  playTimeTracker: JobOutpostTypanBotanist
  description: Ботаник из далёкого космоса.
  startingGear: SyndicateBotanist
  icon: "JobIconOutpostTypanBotanist"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:RoleTimeRequirement
      role: JobOutpostTypanAtmosTech
      time: 20600
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 26000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 24000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 19000
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate

- type: startingGear
  id: SyndicateBotanist
  equipment:
    ears: ClothingHeadsetAltOutpostTypan
    jumpsuit: ClothingUniformJumpsuitOutpostTypanBotanist
    back: ClothingBackpackSyndicateFilled
    shoes: ClothingShoesColorBlack
    id: SyndiPDABotan
