# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanMedic
  name: job-name-typan-medic
  playTimeTracker: JobOutpostTypanMedic
  description: Медик из далёкого космоса.
  startingGear: SyndicateParamedic
  icon: "JobIconSyndicateParamedic"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  requirements:
    - !type:RoleTimeRequirement
      role: JobOutpostTypanBotanist
      time: 20600
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 31000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate

- type: startingGear
  id: SyndicateParamedic
  equipment:
    eyes: ClothingEyesHudSyndicateAgentOutpostTypan
    ears: ClothingHeadsetAltOutpostTypan
    jumpsuit: ClothingUniformJumpsuitParamedicSyndie
    outerClothing: ClothingOuterMedOutpostTypan
    shoes: ClothingShoesBootsCombat
    id: MedicalPDASyndi
    back: ClothingBackpackSyndicateFilled
    belt: ClothingBeltMedicalFilled
