# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanRD
  name: job-name-typan-rd
  playTimeTracker: JobOutpostTypanRD
  description: Директор исследований из далёкого космоса.
  startingGear: SyndicateRD
  icon: "JobIconSyndicateRD"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 32000
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 34000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 73000
    - !type:DepartmentTimeRequirement
      department: Frontier
      time: 83000
    - !type:OverallPlaytimeRequirement
      time: 150000
  access:
  - SyndicateAgent
  - NuclearOperative
  - ResearchDirectorTypan
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate

- type: startingGear
  id: SyndicateRD
  equipment:
    eyes: ClothingEyesGlassesHiddenSecurity
    ears: ClothingHeadsetAltOutpostTypan
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterCoatRDOutpostTypan
    gloves: ClothingHandsRDOutpostTypan
    id: SyndiPDARD
    back: ClothingBackpackSyndicateFilled
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    belt: ClothingBeltAssaultOutpostTypan
