# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanScience
  name: job-name-typan-science
  playTimeTracker: JobOutpostTypanScience
  salary: 35000
  description: Учёный из далёкого космоса.
  startingGear: SyndicateScience
  icon: "JobIconSyndicateScience"
  supervisors: job-supervisors-typan-rd
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobOutpostTypanBotanist
      time: 20600
    - !type:DepartmentTimeRequirement
      department: Security
      time: 12000
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 25000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 60000
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled

- type: startingGear
  id: SyndicateScience
  equipment:
    ears: ClothingHeadsetAltOutpostTypan
    jumpsuit: ClothingUniformScienceOutpostTypan
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsScienceOutpostTypan
    shoes: ClothingShoesBootsCombat
    back: ClothingBackpackSyndicateFilled
    id: SyndiPDAScience
