# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanTelecommunicationsOfficer
  name: job-name-typan-telecommunications-officer
  playTimeTracker: JobOutpostTypanTelecommunicationsOfficer
  description: Офицер телекомуникаций из далёкого космоса.
  startingGear: SyndicateFormal
  icon: "JobIconSyndicateFormal"
  supervisors: job-supervisors-typan-syndicate
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 30000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 95000
    - !type:DepartmentTimeRequirement
      department: Frontier
      time: 108000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000
    - !type:OverallPlaytimeRequirement
      time: 360000
  access:
  - SyndicateAgent
  - NuclearOperative
  - TelecomOfficer
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord

- type: startingGear
  id: SyndicateFormal
  equipment:
    eyes: ClothingEyesHudOutpostTypan
    ears: ClothingHeadsetAltOutpostTypan
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    gloves: ClothingHandsGlovesCombat
    id: SyndiPDACom
    back: ClothingBackpackSyndicateFilled
    belt: ClothingBeltAssaultOutpostTypan
    pocket1: SyndicateWhistle
    pocket2: ClothingMaskGasSyndicate
