# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: randomHumanoidSettings
  id: EventNukieOps
  speciesBlacklist:
    # - Arachnid
    - Diona
    # - Dwarf
    # - Human
    # - Moth
    # - Reptilian
    # - SlimePerson
    - Vox
    # - Demon
    # - Shark
    # - Tajaran
    # - Vulpkanin
    - Goblin
    - Harpy
    - Felinid
    - Kobolt
    - XenoSponsor
    - IPC
    - IPS
    # - Avali #рофлсы
  randomizeName: false

#Обычный ЯО
- type: entity
  id: RandomHumanoidSpawnerNukeOperative
  categories: [ HideSpawnMenu ]
  name: Ядерный оперативник
  suffix: ЯО, Оперативник
  components:
    - type: Sprite
      layers:
        - sprite: Clothing/OuterClothing/Hardsuits/syndicate.rsi
          state: icon
        - sprite: Markers/cross.rsi
          state: blue
    - type: RandomMetadata
      nameSegments:
      - SyndicateOpPrefix
      - SyndicateNamesNormal
    - type: RandomHumanoidSpawner
      settings: NukeOperativePreset
- type: randomHumanoidSettings
  id: NukeOperativePreset
  parent: EventNukieOps
  components:
    - type: GhostTakeoverAvailable
    - type: GhostRole
      name: roles-antag-nuclear-operative-name
      description: roles-antag-nuclear-operative-objective
      rules: ghost-role-information-rules-default-team-antagonist
      requirements:
      - !type:DepartmentTimeRequirement
        department: Medical
        time: 36000 # 10 hours
      - !type:DepartmentTimeRequirement
        department: Security
        time: 72000 # 20 hours
      raffle:
        settings: default
    - type: NukeOperative
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: Loadout
      prototypes: [ SyndicateOperativeGearFull ]

#ЯО Кома
- type: entity
  id: RandomHumanoidSpawnerNukeopsCommander
  categories: [ HideSpawnMenu ]
  name: Ядерный оперативник
  suffix: ЯО, Командир
  components:
    - type: Sprite
      layers:
        - sprite: Clothing/OuterClothing/Hardsuits/syndieelite.rsi
          state: icon
        - sprite: Markers/cross.rsi
          state: blue
    - type: RandomMetadata
      nameSegments:
      - SyndicateComOpPrefix
      - SyndicateNamesNormal
    - type: RandomHumanoidSpawner
      settings: NukeopsCommanderPreset
- type: randomHumanoidSettings
  id: NukeopsCommanderPreset
  parent: EventNukieOps
  components:
    - type: GhostTakeoverAvailable
    - type: GhostRole
      name: roles-antag-nuclear-operative-commander-name
      description: roles-antag-nuclear-operative-commander-objective
      rules: ghost-role-information-rules-default-team-antagonist
      requirements:
      - !type:DepartmentTimeRequirement
        department: Medical
        time: 108000 # 30 hours
      - !type:DepartmentTimeRequirement
        department: Security
        time: 72000 # 20 hours
      - !type:DepartmentTimeRequirement
        department: Command
        time: 72000 # 20 hours
      raffle:
        settings: default
    - type: NukeOperative
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: Loadout
      prototypes: [ SyndicateCommanderGearFull ]

#ЯО Медик
- type: entity
  id: RandomHumanoidSpawnerNukeopsMedic
  categories: [ HideSpawnMenu ]
  name: Ядерный оперативник
  suffix: ЯО, Медик
  components:
    - type: Sprite
      layers:
        - sprite: Clothing/OuterClothing/Hardsuits/syndieelite.rsi
          state: icon
        - sprite: Markers/cross.rsi
          state: blue
    - type: RandomMetadata
      nameSegments:
      - SyndicateOpPrefix
      - SyndicateNamesNormal
    - type: RandomHumanoidSpawner
      settings: NukeopsMedicPreset
- type: randomHumanoidSettings
  id: NukeopsMedicPreset
  parent: EventNukieOps
  components:
    - type: GhostTakeoverAvailable
    - type: GhostRole
      name: roles-antag-nuclear-operative-agent-name
      description: roles-antag-nuclear-operative-agent-objective
      rules: ghost-role-information-rules-default-team-antagonist
      requirements:
      - !type:DepartmentTimeRequirement
        department: Medical
        time: 144000 # 40 hours
      - !type:RoleTimeRequirement
        role: JobChemist
        time: 72000 # 20 hours
      - !type:DepartmentTimeRequirement
        department: Security
        time: 72000 # 20 hours
      raffle:
        settings: default
    - type: NukeOperative
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: Loadout
      prototypes: [ SyndicateOperativeMedicFull ]

# Лона
- type: entity
  id: RandomHumanoidSpawnerLoneNukeOperative
  categories: [ HideSpawnMenu ]
  name: Ядерный оперативник
  suffix: ЯО, Лона
  components:
    - type: Sprite
      layers:
        - sprite: Clothing/OuterClothing/Hardsuits/syndicate.rsi
          state: icon
        - sprite: Markers/cross.rsi
          state: blue
    - type: RandomMetadata
      nameSegments:
      - SyndicateNamesPrefix
      - SyndicateNamesNormal
    - type: RandomHumanoidSpawner
      settings: LoneNukeOperativePreset
- type: randomHumanoidSettings
  id: LoneNukeOperativePreset
  parent: EventNukieOps
  components:
    - type: GhostTakeoverAvailable
    - type: GhostRole
      name: ghost-role-information-loneop-name
      description: ghost-role-information-loneop-description
      rules: ghost-role-information-loneop-rules
      requirements:
      - !type:DepartmentTimeRequirement
        department: Medical
        time: 36000 # 10 hours
      - !type:DepartmentTimeRequirement
        department: Security
        time: 72000 # 20 hours
      raffle:
        settings: default
    - type: NukeOperative
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: Loadout
      prototypes: [ SyndicateLoneOperativeGearFull ]

- type: entity
  parent: [ MedicalPodSyndie, MedicalPod ]
  id: MedicalPodSyndieNukeOperative
  suffix: Под, ЯО
  components:
  - type: StorageFill
    contents:
    - id: RandomHumanoidSpawnerNukeOperative
      orGroup: body
      prob: 1
  - type: Icon
    sprite:  _Lua/Structures/Storage/emergency_pod.rsi
    state: icon
  - type: Sprite
    noRot: true
    sprite: _Lua/Structures/Storage/emergency_pod.rsi
    layers:
    - state: base
      map: ["enum.StorageVisualLayers.Base"]
    - state: window-closed
      map: ["enum.StorageVisualLayers.Door"]
    - state: antenna-unlit
      shader: unshaded
    - state: healthanalyzer-unlit
      shader: unshaded
      map: ["healthanalyzer"]
    - state: occupied-unlit
      shader: unshaded
      map: ["occupied"]

- type: entity
  parent: [ MedicalPodSyndie, MedicalPod ]
  id: MedicalPodSyndieNukeOperativeMed
  suffix: Под, ЯО Медик
  components:
  - type: StorageFill
    contents:
    - id: RandomHumanoidSpawnerNukeopsMedic
      orGroup: body
      prob: 1
  - type: Icon
    sprite:  _Lua/Structures/Storage/emergency_pod.rsi
    state: icon
  - type: Sprite
    noRot: true
    sprite: _Lua/Structures/Storage/emergency_pod.rsi
    layers:
    - state: base
      map: ["enum.StorageVisualLayers.Base"]
    - state: window-closed
      map: ["enum.StorageVisualLayers.Door"]
    - state: antenna-unlit
      shader: unshaded
    - state: healthanalyzer-unlit
      shader: unshaded
      map: ["healthanalyzer"]
    - state: occupied-unlit
      shader: unshaded
      map: ["occupied"]

- type: entity
  parent: [ MedicalPodSyndie, MedicalPod ]
  id: MedicalPodSyndieNukeOperativeComa
  suffix: Под, ЯО Командир
  components:
  - type: StorageFill
    contents:
    - id: RandomHumanoidSpawnerNukeopsCommander
      orGroup: body
      prob: 1
  - type: Icon
    sprite:  _Lua/Structures/Storage/emergency_pod.rsi
    state: icon
  - type: Sprite
    noRot: true
    sprite: _Lua/Structures/Storage/emergency_pod.rsi
    layers:
    - state: base
      map: ["enum.StorageVisualLayers.Base"]
    - state: window-closed
      map: ["enum.StorageVisualLayers.Door"]
    - state: antenna-unlit
      shader: unshaded
    - state: healthanalyzer-unlit
      shader: unshaded
      map: ["healthanalyzer"]
    - state: occupied-unlit
      shader: unshaded
      map: ["occupied"]

- type: entity
  parent: [ MedicalPodSyndie, MedicalPod ]
  id: MedicalPodSyndieNukeOperativeLone
  suffix: Под, ЯО Одинокий
  components:
  - type: StorageFill
    contents:
    - id: RandomHumanoidSpawnerLoneNukeOperative
      orGroup: body
      prob: 1
  - type: Icon
    sprite:  _Lua/Structures/Storage/emergency_pod.rsi
    state: icon
  - type: Sprite
    noRot: true
    sprite: _Lua/Structures/Storage/emergency_pod.rsi
    layers:
    - state: base
      map: ["enum.StorageVisualLayers.Base"]
    - state: window-closed
      map: ["enum.StorageVisualLayers.Door"]
    - state: antenna-unlit
      shader: unshaded
    - state: healthanalyzer-unlit
      shader: unshaded
      map: ["healthanalyzer"]
    - state: occupied-unlit
      shader: unshaded
      map: ["occupied"]
