# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingDeathSquadronBackpack
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetDeathSquad
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: EnergySword
    belt: ClothingBeltDeathSquadWebbingFilled
    underwearb: ClothingUnderwearBottomBoxersDeathSquad
  storage:
    back:
    - CombatMedipen
    - CombatMedipen
    - CombatMedipen
    - CombatMedipen
    - CombatMedipen
    - CombatMedipen
    - C4
    - C4
    - C4
    - C4
    - NFWeaponEnergyRiflePulse
    - NFWeaponRevolverWard45
    - NFSpeedLoaderPistol45Uranium
    - NFSpeedLoaderPistol45Uranium
    - NFSpeedLoaderPistol45Uranium
    - NFSpeedLoaderPistol45Uranium
    - NFSpeedLoaderPistol45Uranium
    - NFSpeedLoaderPistol45Uranium
    - NFSpeedLoaderPistol45Uranium
    - NFSpeedLoaderPistol45Uranium
    - PinpointerNuclear
    - BoxHandcuff
    - EnergyShield
    - JawsOfLife
    - NukeCodePaper

- type: entity
  parent: ClothingBeltSecurityWebbing
  id: ClothingBeltDeathSquadWebbingFilled
  name: РПС эскадрона смерти
  description: РПС члена отряда элитной эвакуации.

- type: entity
  parent: ClothingHeadset
  id: ClothingHeadsetDeathSquad
  name: мастер гарнитура
  description: Уникальный образец гарнитуры c доступом во все каналы.
  suffix: Эскадрон смерти
  components:
  - type: ContainerFill
    containers:
      key_slots:
      - EncryptionKeyKSO
      - EncryptionKeyCentCom
      - EncryptionKeyStationMaster
      - EncryptionKeyFreelance
      - EncryptionKeyDeathSquad
  - type: Sprite
    sprite: Clothing/Ears/Headsets/base.rsi
  - type: Clothing
    sprite: Clothing/Ears/Headsets/base.rsi
  - type: Headset
