# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: CentralCommandOfficer
  name: job-name-centcom-officer
  description: job-description-centcom-officer
  playTimeTracker: JobCentralCommandOfficer
  setPreference: false
  startingGear: CentcomOfficerGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom-administrator
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomOfficerGear
  equipment:
    jumpsuit: ADTClothingUniformTurleneckGreenBlack
    back: ClothingBackpack
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterVestWeb
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretCentcomNaval
    id: CentcomPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetCentCom
    belt: ClothingBeltAssaultOutpostTypan
  #   underwearb: ClothingUnderwearBottomBoxersCentcomm
  # underweart: ClothingUnderwearTopBraCentcomm
  # underwearb: ClothingUnderwearBottomPantiesCentcomm
  # innerClothingSkirt: ClothingUniformCentcomOfficial
  # storage:
  #   back:
  #   - 
