- type: job
  id: CentralCommandAssistant
  name: job-name-centcomassistant
  description: job-description-centcomassistant
  playTimeTracker: JobCentralCommandAssistant
  setPreference: true
  startingGear: CentComInternGear
  icon: JobIconServiceWorker
  supervisors: job-supervisors-centcommembers
  canBeAntag: false
  weight: 1
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelisted: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 64800 # 18 hours
    - !type:OverallPlaytimeRequirement
      time: 121600 # 6 hours
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 108000
  access:
    - CentralCommand
    - Service
    - Maintenance
    - Bar
    - Kitchen
    - Hydroponics
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
            - CentralCommand
        - type: AntagImmune
        - type: Company
          companyName: CentComm

- type: startingGear
  id: CentComInternGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomIntern
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: CentcomInternPDABackmen
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: CentComInternGearArmed # POWER IN QUANTITY!
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomIntern
    back: WeaponSniperMosin
    shoes: ClothingShoesColorBlack
    eyes: ClothingEyesGlassesSunglasses
    neck: CombatKnife
    id: CentcomInternPDABackmen
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesFingerless
    head: ClothingHeadHatCorpsoft
    pocket1: MedicatedSuture
    pocket2: MagazineBoxLightRifle
    outerClothing: ClothingOuterArmorBasic

- type: entity
  parent: BasePDA
  id: CentcomInternPDABackmen
  name: CentCom Assistant PDA
  description: Light green sign of walking bureaucracy.
  components:
    - type: Appearance
      appearanceDataInit:
        enum.PdaVisuals.PdaType:
          !type:String
          pda-centcom
    - type: Pda
      id: IDCardCentComIntern
      penSlot:
        startingItem: PenCentcom
        whitelist:
          tags:
            - Write
    - type: PdaBorderColor
      borderColor: "#00842e"
    - type: Icon
      state: pda-centcom

- type: entity
  parent: CentcomIDCardDeathsquad
  id: IDCardCentComIntern
  name: ID карта Ассистента ЦК
  components:
    - type: Sprite
      sprite: Backmen/Objects/Misc/id_cards.rsi
      layers:
      - state: card_centcom # Backmen
      - state: sub_department # Backmen
        color: "#0F4162"
      - state: frame_head # Backmen
        color: "#0F4162"
      - state: idintern-service
    - type: PresetIdCard
      job: CentralCommandAssistant
    - type: Access
      tags:
        - CentralCommand
        - Service
        - Maintenance
        - Bar
        - Kitchen
        - Hydroponics
